### ISSUE TITLE
[PS #화난다] 2022-05-20 (금)

### ISSUE THREAD

**Issue by chobe111** [Pushpull7381/everyday_study#67]
![image](https://user-images.githubusercontent.com/40628765/169578610-242048d1-d7b2-4077-9ea2-0c2c24d8080b.png)

SCC + INDEG 로 풀수있는 문제 
INDEG STACK으로 구현하다 터져버려서 QUEUE로 구현할까 생각했지만 위상정렬을 할 필요도 없는 문제

**Comment by skd6150** [comment]
나이따!!
